name: Auto-merge dependabot updates
on:
  schedule:
    - cron: "0 11,18 * * *"
jobs:
  test:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          auto-merge: minor
          merge-method: squash