name: CI
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable
        yarn ${{ matrix.step }}
